### ISSUE TITLE
پیشنهاد ایجاد یک گروه تلگرامی برای بحث

### ISSUE THREAD

**Issue by bahramevarjavand** [nahankhah/nahankhah.github.io#4]
سلام پیشنهاد می کنم یک گروه تلگرامی برای بحث ایجاد شود.

**Comment by bahramevarjavand** [comment]
یا فعال کردن قسمت discussion برای بحث

**Comment by nahankhah** [comment]
گروه تلگرامی وجود داره در حال حاضر
