### ISSUE TITLE
FreeZiyaSadr

### ISSUE THREAD

**Issue by mgatmiri** [nahankhah/nahankhah.github.io#46]
### Your name

```NAME Majid Gatmiri```

### Your email

```EMAIL _No response_```

**Comment by nahankhah** [comment]
ایشو رو جهت قابل پردازش بودن برای اسکریپت، تغییر دادیم.

**Comment by nahankhah** [comment]
closed by: https://github.com/nahankhah/nahankhah.github.io/pull/62
